apiVersion: flagger.app/v1beta1
kind: Canary
metadata:
  name: hello-service
  namespace: asm-showcase
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: hello-service
  # the maximum time in seconds for the canary deployment
  # to make progress before it is rollback (default 600s)
  progressDeadlineSeconds: 60
  service:
    port: 80
    targetPort: 8080
    gateways:
      - my-gateway
    hosts:
      - anthos.gcp-demo.be-svc.at
    trafficPolicy:
      tls:
        mode: ISTIO_MUTUAL
  analysis:
    # schedule interval (default 60s)
    interval: 1m
    # max number of failed metric checks before rollback
    threshold: 5
    # max traffic percentage routed to canary
    # percentage (0-100)
    maxWeight: 50
    # canary increment step
    # percentage (0-100)
    stepWeight: 10
    metrics:
      - name: "500s percentage"
        templateRef:
          name: 500-percentage
          namespace: asm-showcase
        thresholdRange:
          min: 0
          max: 5
        interval: 1m
#      - name: request-success-rate
#        # minimum req success rate (non 5xx responses)
#        # percentage (0-100)
#        thresholdRange:
#          min: 99
#        interval: 1m
#      - name: request-duration
#        # maximum req duration P99
#        # milliseconds
#        thresholdRange:
#          max: 500
#        interval: 30s
