apiVersion: flagger.app/v1beta1
kind: MetricTemplate
metadata:
  name: 500-percentage
  namespace: asm-showcase
spec:
  provider:
    type: prometheus
    address: http://prom-frontend.monitoring:9090
  query: |
    100 * (
      sum(
        rate(
          istio_io:service_server_request_count{
            monitored_resource="istio_canonical_service",
            destination_workload_name="{{ target }}",
            destination_workload_namespace="{{ namespace }}",
            response_code="500"
          }[1m]
        )
      ) /
      sum(
        rate(
          istio_io:service_server_request_count{
            monitored_resource="istio_canonical_service",
            destination_workload_name="{{ target }}",
            destination_workload_namespace="{{ namespace }}"
          }[1m]
        )
      )
    )
    

# 100 - sum(rate(istio_io:service_server_request_count{monitored_resource="istio_canonical_service",destination_workload_name="main-client-application-manager",destination_workload_namespace="cam",response_code="200"}[${__interval}])) / sum(rate(istio_io:service_server_request_count{monitored_resource="istio_canonical_service",destination_workload_name="main-client-application-manager",destination_workload_namespace="cam"}[${__interval}])) * 100

#  100 * (sum(rate(istio_io:service_server_request_count{monitored_resource="istio_canonical_service",destination_workload_name="main-client-application-manager-token-provider-api-gw",destination_workload_namespace="cam",response_code="200"}[${__interval}])) /
#  sum(rate(istio_io:service_server_request_count{monitored_resource="istio_canonical_service",destination_workload_name="main-client-application-manager-token-provider-api-gw",destination_workload_namespace="cam"}[${__interval}])))
