apiVersion: networking.gke.io/v1
kind: MultiClusterService
metadata:
  name: anthos-ingress-service
  namespace: asm-usecase  
  annotations:
    cloud.google.com/backend-config: '{"ports": {"http":"ingress-backendconfig"}}'
    networking.gke.io/app-protocols: '{"http":"HTTP"}'
spec:
  template:
    spec:
      selector:
        istio: ingressgateway
      ports:
        - name: http
          protocol: TCP
          port: 80

---
apiVersion: networking.gke.io/v1
kind: MultiClusterIngress
metadata:
  name: anthos-ingress-gateway
  namespace: asm-usecase
  annotations:
    networking.gke.io/pre-shared-certs: "usecase-cert"
    networking.gke.io/static-ip: https://www.googleapis.com/compute/v1/projects/asm-showcase-6312a455/global/addresses/usecase-ingress-api
spec:
  template:
    spec:
      backend:
        serviceName: anthos-ingress-service
        servicePort: 80
      rules:  
      - host: "usecase.gcp-demo.be-svc.at"
        http:
          paths:
          - backend:
              serviceName: anthos-ingress-service
              servicePort: 80        
---
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: ingress-backendconfig
  namespace: asm-usecase  
spec:
  healthCheck:
    requestPath: /healthz/ready
    port: 15021
    type: HTTP        