apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-service-v2
  namespace: asm-usecase
spec:
  selector:
    matchLabels:
      app: hello-service
      version: v2
  template:
    metadata:
      labels:
        app: hello-service
        version: v2
    spec:
      containers:
        - name: hello-service
          image: nicholasjackson/fake-service:v0.26.0
          imagePullPolicy: IfNotPresent
          readinessProbe:
            httpGet:
              port: 8080
              path: /ready
          livenessProbe:
            httpGet:
              port: 8080
              path: /health
          env:
            - name: LISTEN_ADDR
              value: '0.0.0.0:8080'
            - name: MESSAGE
              value: 'Hello from v2'
          ports:
            - name: http
              containerPort: 8080
