### unauthenticated
GET https://usecase.anthos.gcp-demo.be-svc.at

### user-1-jwt
#{
#  "iss": "https://my-issuer.com",
#  "sub": "user-1",
#  "aud": "hello-service",
#  "exp": 1735689600,
#  "iat": 1563980400
#}
GET https://usecase.anthos.gcp-demo.be-svc.at
Authorization: Bearer eyJraWQiOiIxMjM0NSIsImFsZyI6IlJTMjU2In0K.eyJpc3MiOiJodHRwczovL215LWlzc3Vlci5jb20iLCJzdWIiOiJ1c2VyLTEiLCJhdWQiOiJoZWxsby1zZXJ2aWNlIiwiZXhwIjoxNzM1Njg5NjAwLCJpYXQiOjE1NjM5ODA0MDB9Cg.jwSEPw6xAkliL105qZLiBZaROgJgB0lVlwtSInFvhAMjQQ6vcO_eetigH0v1OTsDpwAr28FMkbl1AkVaASqZV8I0hGyVQ0htxvivEQUj3StfQw0m1hDpwCbqtijPnup_-0MFdBNm74CQEwLzXxOC5mBZPkBFSs-atN1epYVf3j4GTOPJEF0IWWnIxhG2XnxUqtM_RCKsH8S5GqXo-wWZOv-Vj5B5_09JML5RNekBa6rvivES00r1Sl4zVteKNYS7QK3n9fPXibAOcVKBvpEb3fXeYR0418WFdWVhzy-Ji3Wn_TNZ0HsIIBQCJzXeLTTXfrStkm4PirvEn74KWkQRKw

### user-2-jwt
#{
#  "iss": "https://my-issuer.com",
#  "sub": "user-2",
#  "aud": "hello-service",
#  "exp": 1735689600,
#  "iat": 1563980400
#}
GET https://usecase.anthos.gcp-demo.be-svc.at
Authorization: Bearer eyJraWQiOiIxMjM0NSIsImFsZyI6IlJTMjU2In0K.eyJpc3MiOiJodHRwczovL215LWlzc3Vlci5jb20iLCJzdWIiOiJ1c2VyLTIiLCJhdWQiOiJoZWxsby1zZXJ2aWNlIiwiZXhwIjoxNzM1Njg5NjAwLCJpYXQiOjE1NjM5ODA0MDB9Cg.03AOFawmsR5hd60qXIUaShGmap_clAxjw3iWhp1krclBzxxzD-9xe-slt_dYjVlvgLcdNPPc_pz23nN5y7iVpN-NzpizJwY9uP_dllIwwbrcxPsvgqNDS8d5hJck3XWCE6C5lwInXVXq1czw5mo7o97gQOgRtmyfgIIJW_gjr2CZZVPjT7XumqXT4zrePtXWFAL3sObjLRDKv7rjiada-Si_Ch16yLP0Z-gs8avzURQLtK9zyuMapHMuvWoOmH7j6yhMaFPvcl4Js9_SHgRG4pB7O2KC7zj5lml3f9RahowC1VA_hTuiCQ9g5GzheARg_jq2X52LTzbAEFWn57Imkw



### health check
GET https://usecase.anthos.gcp-demo.be-svc.at/health
