apiVersion: apps/v1
kind: Deployment
metadata:
  name: secure-service
  namespace: asm-usecase
spec:
  selector:
    matchLabels:
      app: secure-service
      version: v1
  template:
    metadata:
      labels:
        app: secure-service
        version: v1
    spec:
      containers:
        - name: secure-service
          image: nicholasjackson/fake-service:v0.26.0
          imagePullPolicy: IfNotPresent
          readinessProbe:
            httpGet:
              port: 8080
              path: /ready
          livenessProbe:
            httpGet:
              port: 8080
              path: /health
          env:
            - name: LISTEN_ADDR
              value: '0.0.0.0:8080'
            - name: MESSAGE
              value: 'Hello World from the secured service!'
          ports:
            - name: http
              containerPort: 8080
          resources:
            limits:
              cpu: 150m
              memory: 256Mi
            requests:
              cpu: 25m
              memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: secure-service
  namespace: asm-usecase
  labels:
    app: secure-service
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
  selector:
    app: secure-service
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: secure-service
  namespace: asm-usecase
spec:
  hosts:
    - 'secure-service.anthos.gcp-demo.be-svc.at'
  gateways:
    - my-gateway
  http:
    - name: secure-service
      route:
        - destination:
            host: secure-service.asm-usecase.svc.cluster.local
