apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: my-gateway
  namespace: asm-showcase
spec:
  selector:
    istio: ingressgateway
    app: asm-ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - '*'
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: test-route
  namespace: asm-showcase  
spec:
  hosts:
  - '*'
  gateways:
  - my-gateway
  http:
  - name: "httpbin"
    match:
    - uri:
        prefix: "/httpbin/"  
    rewrite:
      uri: "/"        
    route:
    - destination:
        host: httpbin
