apiVersion: v1
data:
  mesh: |-
    defaultConfig:
      tracing:
        stackdriver: {}
    accessLogFile: /dev/stdout
    defaultConfig:
      tracing:
        stackdriver: {}    
kind: ConfigMap
metadata:
  name: istio-asm-managed
  namespace: istio-system
